python BlockchainSimulator.py -c 12000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 18000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 24000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 30000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 36000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 42000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 48000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 54000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 60000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 66000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 72000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False
python BlockchainSimulator.py -c 78000 -t 1 --RANDOM_TRANS True --RANDOM_WINNERS True --RANDOM_CONNECT True --RANDOM_START_CONNECT False