call autorun_RT_RW_RC_RSC.bat 20 3 Stats
call autorun_RT_RW_RC_RSC.bat 30 3 Stats
call autorun_RT_RW_RC_RSC.bat 40 3 Stats
call autorun_RT_RW_RC_RSC.bat 50 3 Stats
call autorun_RT_RW_RC_RSC.bat 60 3 Stats
call autorun_RT_RW_RC_RSC.bat 20 3 Stats1
call autorun_RT_RW_RC_RSC.bat 30 3 Stats1
call autorun_RT_RW_RC_RSC.bat 40 3 Stats1
call autorun_RT_RW_RC_RSC.bat 50 3 Stats1
call autorun_RT_RW_RC_RSC.bat 60 3 Stats1
