call autorun_RT_RW_RC_RSC.bat 20 6 Stats1
call autorun_RT_RW_RC_RSC.bat 20 9 Stats1
call autorun_RT_RW_RC_RSC.bat 20 6 Stats2
call autorun_RT_RW_RC_RSC.bat 20 9 Stats2
call autorun_RT_RW_RC_RSC.bat 20 6 Stats3
call autorun_RT_RW_RC_RSC.bat 20 9 Stats3
call autorun_RT_RW_RC_RSC.bat 20 6 Stats4
call autorun_RT_RW_RC_RSC.bat 20 9 Stats4
call autorun_RT_RW_RC_RSC.bat 20 6 Stats5
call autorun_RT_RW_RC_RSC.bat 20 9 Stats5