import os


NUM_OF_NODES = 20
NUM_OF_WINNERS = 3
CONTACT_FREQ = 0
TRANS_RATE = 20
RANDOM_TRANS = False  # _RT
RANDOM_WINNERS = False  # _RW
RANDOM_START_CONNECT_TIME = True  # _RSC
RANDOM_CONNECT_TIME = True  # _RC
OUTPUT_FILE = ""
STATS_DIRECTORY = os.getcwd()+"\\Stats\\"
HETERO_DIRECTORY = os.getcwd()+"\\Hetero_log\\"
HETERO_RSC = False
HETERO_RC = False